### ISSUE TITLE
:bug: Documentation typos 

### ISSUE THREAD

**Issue by lmrb-1968** [xygeni/xygeni-action#24]
There are some documentation issues.

- Under `Add a step calling the action`, the pattern specified `.github/*.yml` is not correct. The correct one is `.github/workflows/*.yml`

- The version tag is 2.0 in the examples, should be updated with the latest version.

- `--fail=severity:critical` does not work. `--fail=critical` is the right syntax.

- The example at the end could use multi-line command using the "block chomp & strip" `>-` YAML operator, for clarity:

```yaml
  - name: Xygeni-Scanner
    uses: xygeni/xygeni-action@v2.1
    id: Xygeni-Scanner
    with:
      token: ${{ secrets.XYGENI_TOKEN }}
      command: >-
         scan -n ${{ github.repository }} -d ${{ github.repository }}
              --run=secrets,iac --fail-on=critical
```

- Probably a final note recommending _action version pinning_ (using the SHA for the action tag) should be recommended, to follow Xygeni's recommendation for pinning action versions. Proposed text:

```md
NOTE: You may use pinned versions for the action, using the immutable commit SHA instead of version numbers, as specified in [Pin actions to full length commit SHA](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
```

Please compare this with the ascidoc version in Xygeni documentation (in development environment) with the fixed issues.
